### ISSUE TITLE
Core Dependents in UD v2

### ISSUE THREAD

**Issue by manning** [UniversalDependencies/UD_v2#10]
- Keep the core-oblique distinction and work out more detailed guidelines for how to apply it in different languages.

In favor.
- Replace the relations dobj and iobj by a single relation obj (with language-specific subtypes obj:dir and obj:ind)
- Remove the relations nsubjpass and csubjpass (and replace auxpass by an optional aux:pass)

I'm basically opposed to these two changes. One way to assuage my concerns is just to use obj:dir, obj:ind, nsubj:pass and csubj:pass, but I tend to feel that those relations are on the wrong side of what should really be regarded as "language (family) particular relations", as they are best seen as universal notions - in the sense of part of the main sweep of language typology, not claiming that all languages have everything; some languages don't have passives at all.

I already wrote some stuff about this on http://universaldependencies.org/v2/core_dependents.html . In brief, these two distinctions clearly in some sense add some "semantics" or at least notions of "argument structure". However, many linguists would argue that "argument structure" exists as part of syntax rather than really being semantics; see e.g., http://www.oxfordbibliographies.com/view/document/obo-9780199772810/obo-9780199772810-0099.xml . At any rate, my main motivation for keeping them is thinking them universal-enough and important-enough for basic textual understanding tasks, like relation extraction, etc.) that they are worth having. I think they can be define in less Eurocentric ways:

nsubj: A grammatical subject/pivot/A or S core argument that is also the "proto-agent" (most-agent-like argument in the sense of Dowty 1991).
nsubjpass: A grammatical subject/pivot/A or S core argument that is _not_ the "proto-agent" (most-agent-like argument in the sense of Dowty 1991).

dobj: An object/O/P core argument that is also the "proto-patient" (most-patient-like argument in the sense of Dowty 1991).
iobj: An object/O/P core argument that is _not_ the "proto-patient" (most-patient-like argument in the sense of Dowty 1991).

I think these definitions accord well with typology, and incorporate a notion of markedness - nsubj and dobj are usual; nsubjpass and iobj are marked mappings of argument structure to core arguments. They also help with NLU applications a lot, since you won't make major mistakes in interpreting roles of core arguments. And the neutrality of these definitions suggest to me that they work quite reasonably well for causatives, applicatives, and antipassives, as well as passives. One could fault the use of the morpheme "pass", and want something more typologically neutral, but I suspect the broad intelligibility of this term makes it a good choice.
- Split the modifier relation nmod into two new relations anom and advnom

Strongly in favor!

**Comment by jnivre** [comment]
I have thought a lot about indirect objects and the risk that the distinction between direct and indirect objects will simply be lost if we make it optional. In addition, there is the argument that indirect objects are a tricky borderline case for the core-oblique distinction and therefore should be treated as universal even though they do not appear in all languages (as argued by Chris). I have therefore thought about different ways in which we could capture the best of two worlds, and I want to propose two possible revisions of the current v2 draft:

1. Replace “dobj/iobj” with “obj” (as in the current draft) but make the subtype “:ind” obligatory for sentences with two objects. That is, if people think there should be two objects in a clause, they will be required to mark one as indirect. Failure to do so could easily be caught in validation, and in this way we would make sure that the information isn’t lost. Also, under this scheme, some treebank developers will be less likely to default to “iobj” for anything that is in dative case.

2. Keep “iobj" as universal to get a more fine-grained obliqueness hierarchy (nsubj > (d)obj > iobj > oblique) but rename “dobj” and call it “obj” instead. This may seem like only a cosmetic change, but I have the impression that the “d” in “dobj” is what is causing a lot of happiness among users who rather want to use “iobj” for single objects in oblique cases. With these names, it is easier to see “obj” as the “unmarked” alternative.

What do you all think?

**Comment by dan-zeman** [comment]
Is alternative (2) meant to include the requirement from (1) that one clause never contains two or more arguments labeled `obj`, i.e. the oversize objects must be `iobj`? (I think it is, even UD v1 guidelines imply this constraint.)

Should we extend the rule and say that `ccomp` and `xcomp` are at the same level with `obj`, i.e. they cannot co-occur with an `obj` in one clause?

On the other hand, an `iobj` can occur without `obj`, which could be elided, right?

**Comment by jnivre** [comment]
Yes, both alternatives exclude more than one "obj" in the same sentence. In (1) you have to use "obj:ind" for the second one, and for (2) you have to use "iobj". 

Yes, the idea is still that "ccomp" and "xcomp" fills an "obj" slot, so to speak.

Yes, "iobj" can occur without "obj" (only) in the case of ellipsis.

**Comment by dan-zeman** [comment]
I think I am fine with any of the two proposals then. I suspect that this is not the end of the story because I am not 100% sure that I am applying Dixon's S-A-O functions as they were intended. But let's leave such discussion for the post-v2 future. Using `obj` in places where I previously used `dobj` is an improvement, as I see it.

**Comment by mcdm** [comment]
I prefer proposition 2. I am not convinced that having a subtype that is obligatory in some cases is the best way to go. This seems to only introduce another "level" (obligatory subtype, between optional subtype and "universal" relation), which I don't think is necessary.

**Comment by manning** [comment]
In favor of 2 and all the recent comments above – I guess that's pretty obvious.

BTW, there's been quite a bit of conversation off-GitHub between me, @jnivre and Bill Croft on how to define core vs. obl and subj/obj/iobj in the most typologically good way (though nothing is water-tight). It'd be good to capture some of that. What's the plan for documentation? Should we already be working on the content of a UD v2 documentation site? I suspect that could be useful in a "build early, build often" way, rather than only having a huge amount of discussion spread over GitHub issues and email….

**Comment by jnivre** [comment]
My plan is definitely to update the criteria for the core-oblique distinction. I just wanted to come to decisions on all the outstanding issues before starting to update the documentation, but perhaps it is better to start doing things incrementally. What we definitely want to avoid, I think, is a situation where some parts of the documentation are v2 and some parts remain v1 and it is not clear to users which is which. Perhaps we should start over with an (almost) empty documentation and only import old sections after they have been checked for v2 conformance.

@fginter @spyysalo @dan-zeman Any ideas on how to best make a smooth transition from v1 to v2 docs?

**Comment by jnivre** [comment]
Some votes for and none against keeping "iobj" and renaming "dobj" to "obj" (instead of merging "iobj" and "dobj" to "obj"). Since this also has the support of Ginter's Razor (because "iobj" does not have to be renamed at all), this is what I will put in the final v2 proposal.
