### ISSUE TITLE
Naming the split nmod relation

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/UD_v2#22]
The v2 draft proposes to split the nmod relation into one relation for modifiers of predicates and one relation for modifiers of nominals, tentatively named "advnom" and "anom". After some offline discussion, I would like to propose that we use the names "obl" and "nmod" instead. The name "obl" (for "oblique") is well established in the language typology literature and fits well into the UD taxonomy, where the core-oblique distinction is central. And if we adopt "obl" for dependents of predicates, we are free to use "nmod" (together with "amod", "nummod") for dependents of nominals. The names "advnom" and "anom" (which I coined myself) follow the same pattern as "advcl"-"acl" and "advmod"-"amod", but (unlike these) they don't have any precedent in the grammatical tradition, which makes them opaque for most UD users. Therefore, I think "obl" and "nmod" will gain acceptance more easily in the community.

**Comment by dan-zeman** [comment]
Does `obl` "oblique" mean the same thing as `advmod` "adverbial nominal"? Doesn't "oblique" imply "oblique argument", which would bring back the argument-adjunct distinction? Or would we use `obl` both for "to John" (in "I gave the book to John") and for "on Saturday" (in "I will come on Saturday")?

**Comment by jnivre** [comment]
Yes. Oblique here just means non-core and covers (oblique) arguments as well as adjuncts.

**Comment by jnivre** [comment]
There seems to be a majority (mostly expressed by email) for obl-nmod over advnom-anom.
