### ISSUE TITLE
New functional relations?

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/UD_v2#23]
When discussing UD from a language typology perspective, Bill Croft suggested three new functional relations:

clf for classifier
idx for index marker
lnk for linker

Classifiers are discussed in #21 and are probably the strongest candidate. 

The index relation would be for cases where an index/agreement marker is at least orthographically a separate word. However, given our decision to accept spaces in words, there may not be any need for this, especially since this is described by Bill as "very very rare".

Here is what Bill has to say about linkers: "Linkers are forms that relate two content words that are so grammaticalized that their origin as either case or idx (actually, det in UD terms) is opaque or at least debatable. Typically linkers contrast with no other overt forms (so they don't have a specific meaning like a case marker), or at most with simple juxtaposition. Persian izafet is a good example of a linker, also the modifying linker in Austronesian languages (where the term originated, I think). I would also argue that English -'s is a linker."

The question is whether it will be acceptable to treat these as "case", possibly with subtypes, or whether we really need a new relation. I am somewhat familiar with Persian ezafe, which has multiple  functions. Some of them are similar to the English -'s, except that the marking goes on the head instead of on the dependent. Therefore, it may be awkward to call it case. On the other hand, unless I am mistaken, it is not usually a separate word in Persian. I would be inclined not to do anything about the linker case until we see a clear need for it (v3?).

**Comment by dan-zeman** [comment]
+1 on waiting for more evidence for linkers.

**Comment by jnivre** [comment]
Agreed to add "clf" but none of the others.
