### ISSUE TITLE
Renaming CONJ to CCONJ

### ISSUE THREAD

**Issue by jnivre** [UniversalDependencies/UD_v2#24]
The proposal to rename CONJ to CCONJ is the only remaining change proposal for the universal tag set. Is the motivation for this change really strong enough if we could otherwise leave the tag set completely intact and backward compatible?

**Comment by dan-zeman** [comment]
Hmm, this is a strong argument against changing it :-(

But I think the coincidence between `CONJ` and `conj` is quite unfortunate. Should we instead rename `conj` to `cnjct`?

**Comment by jnivre** [comment]
I like the idea of renaming "conj" instead of "CONJ", since we are renaming a number of dependency relations to improve clarity (but are leaving all the (other) postags as they are). What about "coord", which is used in a number of treebanks. Or is the risk then that it will be taken as short for "coordinating conjunction" or "coordinator" and therefore be confused with "cc"?

**Comment by dan-zeman** [comment]
There is always the risk, unless we create a completely new label like `this_is_really_a_conjunct_and_not_a_conjunction` :-) I just looked into my notes about conversion we did for HamleDT, just a few languages, and compared it to UDv1. Here is what has been used at least once in the sample (lowercased):

- head conjunction: coord
- non-head conjunction: **cc**, **conj**, co, auxy, **coord**, cd, ++
- non-head conjunct: **conj**, conjarg, conjunct, *_co, cj, **coord**, ccof, rel.conj., **cc**

**Comment by jnivre** [comment]
Thanks, Dan. It seems that coord was a bad idea. But none of the others is unambiguous either. Perhaps it is best to keep dependencies as they are and go with CCONJ instead.

**Comment by dan-zeman** [comment]
Agreed, I actually like `CCONJ`.

**Comment by sebschu** [comment]
+1 for `CCONJ`.

**Comment by ftyers** [comment]
+1 for `CCONJ`

**Comment by jnivre** [comment]
Everyone seems to agree that this is a good change, so I am closing the issue.
